#!/usr/bin/env python3
"""Bat-Speaker Stop hook.

Fires when Bruce finishes a turn. If the toggle file ~/.batspeaker-on exists,
it TTS-renders the response into an MP3 and prepends it to a rolling "listen"
note that Obsidian Sync carries to Kyle's phone. Optionally pings Moshi.

Two modes:
  (default)            hook entry: read stdin JSON, extract text, detach worker
  --worker <textfile>  heavy lifting: tts + note update + notify (backgrounded)

Designed to never block or break the CLI turn: always exits 0 on the hook path,
and the slow work runs in a detached child process.
"""
import sys, os, json, re, subprocess, time, glob, traceback

VAULT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TOGGLE = os.path.expanduser("~/.batspeaker-on")
MP3_DIR = os.path.join(VAULT, "3 Information", "Attachments", "batspeaker")
NOTE = os.path.join(VAULT, "0 Inbox", "Bat-Speaker Live.md")
LOG = os.path.expanduser("~/.local/state/batspeaker.jsonl")
WORKER_ERR = os.path.expanduser("~/.local/state/batspeaker-worker.err")
TTS = os.path.expanduser("~/.local/bin/tts")
MOSHI = os.path.expanduser("~/.local/bin/moshi-notify")
VAULT_NAME = "everything"
CLIP_SEP = "<!-- clip -->"
CONFIG = os.path.expanduser("~/.config/batspeaker/config.json")
DEFAULTS = {
    "engine": "openai",    # openai | deepgram | elevenlabs
    "voice": "ash",        # OpenAI voice: alloy/ash/coral/echo/fable/nova/onyx/sage/shimmer
    "model": "tts-1-hd",   # OpenAI model: tts-1 (cheap) or tts-1-hd (quality)
    "deepgram_voice": "orpheus",                  # Deepgram Aura voice (-> aura-<voice>-en)
    "elevenlabs_voice": "nPczCjzI2devNBz1zQrb",   # ElevenLabs Brian
    "elevenlabs_model": "eleven_multilingual_v2",
    "speed": "1.0",        # 0.25–4.0 (OpenAI native; ffmpeg post-process for the others)
    "keep": 15,            # max clips kept in the note
    "min_chars": 12,       # skip responses shorter than this
    "notify": True,        # fire a Moshi push per clip
    "title": "🔊 Bat-Speaker",
    "append_when_off": True,  # when toggle off, still append text (no TTS/push)
}


def load_config():
    """DEFAULTS overlaid with ~/.config/batspeaker/config.json (if present)."""
    cfg = dict(DEFAULTS)
    try:
        with open(CONFIG) as f:
            cfg.update(json.load(f))
    except Exception:
        pass
    return cfg

NOTE_HEADER = """---
created_on: {date}
origin: ai
publish: false
---

_Bruce's spoken responses, newest at top. Auto-generated by the Bat-Speaker Stop hook. Toggle with `batspeaker on|off`. See [[Bat-Speaker — Backlog]]._
"""


def jlog(event, **fields):
    """Append one structured JSONL record. Inspect with: batspeaker log"""
    rec = {"ts": time.strftime("%Y-%m-%dT%H:%M:%S"), "event": event}
    rec.update(fields)
    try:
        os.makedirs(os.path.dirname(LOG), exist_ok=True)
        with open(LOG, "a") as f:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    except Exception:
        pass


# ---------- transcript extraction ----------

def is_real_user(entry):
    if entry.get("type") != "user":
        return False
    content = entry.get("message", {}).get("content")
    if isinstance(content, str):
        return True
    if isinstance(content, list):
        return any(isinstance(b, dict) and b.get("type") == "text" for b in content)
    return False


def extract_last_turn(transcript_path):
    """The final run of assistant prose in the latest turn: text emitted after
    the last tool call. Pre-tool narration ("let me check...") and text from
    prior turns are dropped, so we speak only the conclusion the user reads."""
    run = []
    with open(transcript_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
            except Exception:
                continue
            if is_real_user(e):
                run = []                      # new turn
            elif e.get("type") == "assistant":
                content = e.get("message", {}).get("content")
                if isinstance(content, list):
                    for b in content:
                        if not isinstance(b, dict):
                            continue
                        if b.get("type") == "text":
                            run.append(b.get("text", ""))
                        elif b.get("type") == "tool_use":
                            run = []          # drop narration before a tool call
    return "\n\n".join(c for c in run if c.strip())


def extract_full_turn(transcript_path):
    """ALL assistant prose in the latest turn, including narration emitted
    before tool calls — the full text Kyle would otherwise scroll on the laggy
    Moshi terminal. Used for the written read-along note even when only the
    conclusion (extract_last_turn) is spoken aloud."""
    run = []
    with open(transcript_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
            except Exception:
                continue
            if is_real_user(e):
                run = []                      # new turn
            elif e.get("type") == "assistant":
                content = e.get("message", {}).get("content")
                if isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "text":
                            run.append(b.get("text", ""))  # keep pre-tool narration
    return "\n\n".join(c for c in run if c.strip())


# ---------- markdown -> speech ----------

def sanitize(md):
    s = md
    s = re.sub(r"```.*?```", " ", s, flags=re.DOTALL)        # code fences
    s = re.sub(r"`([^`]*)`", r"\1", s)                        # inline code
    s = re.sub(r"!\[\[[^\]]*\]\]", " ", s)                    # embeds
    s = re.sub(r"\[\[[^\]|]*\|([^\]]*)\]\]", r"\1", s)        # [[a|b]] -> b
    s = re.sub(r"\[\[([^\]]*)\]\]", r"\1", s)                 # [[a]] -> a
    s = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", s)               # md images
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", s)            # md links -> text
    s = re.sub(r"https?://\S+", " ", s)                       # bare urls
    s = re.sub(r"^\s{0,3}#{1,6}\s*", "", s, flags=re.M)       # headings
    s = re.sub(r"^\s{0,3}>\s?", "", s, flags=re.M)            # blockquotes
    s = re.sub(r"^\s*[-*+]\s+", "", s, flags=re.M)            # bullets
    s = re.sub(r"^\s*\d+\.\s+", "", s, flags=re.M)            # numbered lists
    s = re.sub(r"^\s*[-*_]{3,}\s*$", "", s, flags=re.M)       # hr
    s = re.sub(r"[*_~]{1,3}", "", s)                          # emphasis marks
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n{3,}", "\n\n", s)
    return s.strip()


def caption(text, n=160):
    one = re.sub(r"\s+", " ", text).strip()
    return (one[:n].rstrip() + "…") if len(one) > n else one


def as_blockquote(text):
    """Full spoken text as a blockquote, preserving paragraph/line breaks."""
    return "\n".join((f"> {ln}" if ln.strip() else ">") for ln in text.split("\n"))


def duration(path):
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", path],
            capture_output=True, text=True, timeout=10)
        return round(float(out.stdout.strip()))
    except Exception:
        return None


# ---------- note assembly ----------

def split_entries(body):
    parts = [p.strip() for p in body.split(CLIP_SEP)]
    return [p for p in parts if p]


def read_existing_entries():
    if not os.path.exists(NOTE):
        return []
    with open(NOTE) as f:
        content = f.read()
    # everything after the intro line we own; entries live after first CLIP_SEP region
    if CLIP_SEP in content:
        first = content.index(CLIP_SEP)
        return split_entries(content[first:])
    return []


def write_note(entries, keep):
    header = NOTE_HEADER.format(date=time.strftime("%Y-%m-%d"))
    blocks = "\n".join(f"\n{CLIP_SEP}\n{e}\n" for e in entries[:keep])
    with open(NOTE, "w") as f:
        f.write(header + "\n" + blocks + "\n")


def prune_orphan_mp3s(entries):
    referenced = set()
    for e in entries:
        for m in re.findall(r"!\[\[batspeaker/([^\]]+\.mp3)\]\]", e):
            referenced.add(m)
    for path in glob.glob(os.path.join(MP3_DIR, "*.mp3")):
        if os.path.basename(path) not in referenced:
            try:
                os.remove(path)
            except Exception:
                pass


def obsidian_uri():
    from urllib.parse import quote
    rel = "0 Inbox/Bat-Speaker Live"
    return f"obsidian://open?vault={quote(VAULT_NAME)}&file={quote(rel)}"


# ---------- TTS engines ----------

def get_env(name):
    """Env var, falling back to parsing ~/.env.sh (the worker runs detached and
    may not inherit keys the way the `tts` wrapper does)."""
    v = os.environ.get(name)
    if v:
        return v
    try:
        with open(os.path.expanduser("~/.env.sh")) as f:
            for line in f:
                line = line.strip()
                if line.startswith("export "):
                    line = line[7:]
                if line.startswith(name + "="):
                    val = line.split("=", 1)[1].strip()
                    if len(val) >= 2 and val[0] in "\"'" and val[-1] == val[0]:
                        val = val[1:-1]
                    return val
    except Exception:
        pass
    return None


def chunk_text(text, limit):
    """Split into <=limit pieces on paragraph, then sentence, boundaries."""
    if len(text) <= limit:
        return [text]
    chunks, cur = [], ""
    for para in re.split(r"(\n\n+)", text):
        if len(cur) + len(para) <= limit:
            cur += para
        elif len(para) <= limit:
            if cur.strip():
                chunks.append(cur)
            cur = para
        else:
            for sent in re.split(r"(?<=[.!?])\s+", para):
                if len(cur) + len(sent) + 1 <= limit:
                    cur += ((" " if cur else "") + sent)
                else:
                    if cur.strip():
                        chunks.append(cur)
                    cur = sent
    if cur.strip():
        chunks.append(cur)
    return [c for c in chunks if c.strip()]


def concat_mp3s(parts, out):
    listf = out + ".list"
    with open(listf, "w") as f:
        for p in parts:
            f.write(f"file '{p}'\n")
    subprocess.run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", listf,
                    "-c", "copy", out], capture_output=True)
    try:
        os.remove(listf)
    except Exception:
        pass


def apply_speed(path, speed):
    try:
        if float(speed) == 1.0:
            return
    except (ValueError, TypeError):
        return
    tmp = path + ".spd.mp3"
    r = subprocess.run(["ffmpeg", "-y", "-i", path, "-filter:a", f"atempo={speed}",
                        tmp], capture_output=True)
    if r.returncode == 0 and os.path.exists(tmp):
        os.replace(tmp, path)


def _deepgram_one(text, voice, out):
    import urllib.request
    key = get_env("DEEPGRAM_API_KEY")
    if not key:
        raise RuntimeError("DEEPGRAM_API_KEY not found")
    req = urllib.request.Request(
        f"https://api.deepgram.com/v1/speak?model=aura-{voice}-en",
        data=json.dumps({"text": text}).encode(),
        headers={"Authorization": f"Token {key}", "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=120) as resp, open(out, "wb") as f:
        f.write(resp.read())


def synth_deepgram(text, voice, out):
    chunks = chunk_text(text, 1900)          # Deepgram caps ~2000 chars/request
    if len(chunks) == 1:
        _deepgram_one(chunks[0], voice, out)
        return
    parts = []
    for i, c in enumerate(chunks):
        p = out.replace(".mp3", f".part{i}.mp3")
        _deepgram_one(c, voice, p)
        parts.append(p)
    concat_mp3s(parts, out)
    for p in parts:
        try:
            os.remove(p)
        except Exception:
            pass


def synth_elevenlabs(text, voice_id, model_id, out):
    import urllib.request
    key = get_env("ELEVENLABS_API_KEY")
    if not key:
        raise RuntimeError("ELEVENLABS_API_KEY not found")
    req = urllib.request.Request(
        f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
        data=json.dumps({"text": text, "model_id": model_id}).encode(),
        headers={"xi-api-key": key, "Content-Type": "application/json",
                 "Accept": "audio/mpeg"})
    with urllib.request.urlopen(req, timeout=180) as resp, open(out, "wb") as f:
        f.write(resp.read())


def synth(engine, cfg, text, out):
    """Render `text` to mp3 `out` via the chosen engine. Raises on failure."""
    if engine == "openai":
        r = subprocess.run([TTS, "-v", cfg["voice"], "-m", cfg["model"],
                            "-s", str(cfg["speed"]), "-o", out],
                           input=text, capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"tts rc={r.returncode}: {r.stderr.strip()[:200]}")
        return  # OpenAI applies speed natively
    if engine == "deepgram":
        synth_deepgram(text, cfg["deepgram_voice"], out)
    elif engine == "elevenlabs":
        synth_elevenlabs(text, cfg["elevenlabs_voice"], cfg["elevenlabs_model"], out)
    else:
        raise RuntimeError(f"unknown engine: {engine}")
    apply_speed(out, str(cfg.get("speed", "1.0")))


# ---------- worker ----------

def _read_textfile(path):
    """Read and delete a tempfile; '' if missing/unreadable."""
    try:
        with open(path) as f:
            data = f.read()
        os.remove(path)
        return data
    except Exception:
        return ""


def worker(spoken_file, full_file=None, tts=True):
    """Render a Bat-Speaker entry.

    spoken_file  text spoken aloud (the conclusion) — only used when tts=True.
    full_file    full turn text for the written read-along blockquote; falls
                 back to the spoken text if absent/empty.
    tts          when False, append a text-only entry (no MP3, no Moshi push).
                 This is the toggle-off path: read on the phone, no API cost.
    """
    jlog("worker_start", textfile=spoken_file, tts=tts)
    try:
        cfg = load_config()
        spoken = _read_textfile(spoken_file)
        full = _read_textfile(full_file) if full_file else ""
        if not full.strip():
            full = spoken
        if not full.strip():
            jlog("worker", status="error", stage="read_textfile",
                 error="no text to write")
            return

        engine = cfg.get("engine", "openai")
        stamp = time.strftime("%Y%m%d-%H%M%S")
        fname, dur = None, None
        if tts:
            os.makedirs(MP3_DIR, exist_ok=True)
            fname = f"bruce-{stamp}.mp3"
            out = os.path.join(MP3_DIR, fname)
            try:
                synth(engine, cfg, spoken, out)
            except Exception as ex:
                jlog("worker", status="error", stage="tts", engine=engine,
                     error=repr(ex)[:300], tb=traceback.format_exc())
                return
            if not os.path.exists(out):
                jlog("worker", status="error", stage="tts", engine=engine,
                     error="no output produced")
                return
            dur = duration(out)

        dur_str = f" · {dur}s" if dur else ""
        head = f"## {time.strftime('%H:%M')} · {time.strftime('%Y-%m-%d')}{dur_str}"
        audio = f"![[batspeaker/{fname}]]\n\n" if fname else ""
        entry = f"{head}\n{audio}{as_blockquote(full)}"

        try:
            entries = [entry] + read_existing_entries()
            write_note(entries, cfg["keep"])
            prune_orphan_mp3s(entries[:cfg["keep"]])
        except Exception:
            jlog("worker", status="error", stage="write_note", mp3=fname,
                 tb=traceback.format_exc())
            return

        # Moshi ping (best-effort; never fails the run). Audio path only —
        # text-only appends stay silent so keyboard sessions don't spam pushes.
        notified = False
        if tts and cfg["notify"] and os.path.exists(MOSHI):
            try:
                msg = f"{caption(spoken, 90)}{dur_str}\n{obsidian_uri()}"
                mr = subprocess.run([MOSHI, cfg["title"], msg],
                                    capture_output=True, text=True, timeout=15)
                notified = (mr.returncode == 0)
            except Exception as ex:
                jlog("worker", status="warn", stage="moshi", error=repr(ex))

        # Stable clip id for the web server: the MP3 stem when there's audio,
        # else a text-only id. `text` is logged so the server can render the
        # read-along straight from the log (robust even after the note prunes).
        clip_id = f"bruce-{stamp}" if fname else f"text-{stamp}-{os.getpid()}"
        jlog("worker", status="success", id=clip_id, engine=engine, mp3=fname,
             tts=tts, text=full, chars=len(spoken), full_chars=len(full),
             duration=dur, notified=notified)
    except Exception:
        jlog("worker", status="error", stage="unhandled", tb=traceback.format_exc())


# ---------- hook entry ----------

def hook_entry():
    toggle_on = os.path.exists(TOGGLE)
    cfg = load_config()
    # Toggle off used to be a silent no-op. Now (append_when_off) we still write
    # the text to the Live note — just skip the TTS/push — so Kyle can read long
    # replies in Obsidian instead of scrolling the laggy Moshi terminal.
    if not toggle_on and not cfg.get("append_when_off", True):
        return
    try:
        data = json.loads(sys.stdin.read())
    except Exception as ex:
        jlog("hook", status="error", stage="parse_stdin", error=repr(ex))
        return
    tpath = data.get("transcript_path")
    if not tpath or not os.path.exists(tpath):
        jlog("hook", status="skip", reason="no_transcript", transcript_path=tpath)
        return
    min_chars = cfg["min_chars"]
    # The Stop hook can fire a beat before Claude Code flushes the final text
    # block to the transcript, so poll for the conclusion instead of reading once.
    spoken, attempts = "", 0
    try:
        for attempts in range(1, 21):          # up to ~6s
            spoken = sanitize(extract_last_turn(tpath))
            if len(spoken.strip()) >= min_chars:
                break
            time.sleep(0.3)
        full = sanitize(extract_full_turn(tpath))
    except Exception:
        jlog("hook", status="error", stage="extract", tb=traceback.format_exc())
        return
    if not full.strip():
        full = spoken
    # Need *something* worth writing; fall back to full when a turn ends on a
    # tool call with no spoken conclusion (narration-only).
    if len(spoken.strip()) < min_chars and len(full.strip()) < min_chars:
        jlog("hook", status="skip", reason="too_short",
             chars=len(spoken.strip()), full_chars=len(full.strip()),
             attempts=attempts)
        return
    do_tts = toggle_on and len(spoken.strip()) >= min_chars
    pid, ts = os.getpid(), int(time.time())
    spoken_tmp = os.path.join("/tmp", f"batspeaker-{pid}-{ts}.spoken.txt")
    full_tmp = os.path.join("/tmp", f"batspeaker-{pid}-{ts}.full.txt")
    try:
        with open(spoken_tmp, "w") as f:
            f.write(spoken)
        with open(full_tmp, "w") as f:
            f.write(full)
        # detach the slow work so the turn returns immediately; stderr goes to a
        # backstop file in case the worker dies before it can jlog anything.
        with open(WORKER_ERR, "a") as werr:
            subprocess.Popen(
                [sys.executable, os.path.abspath(__file__), "--worker",
                 spoken_tmp, full_tmp, "1" if do_tts else "0"],
                stdout=subprocess.DEVNULL, stderr=werr, start_new_session=True)
        jlog("hook", status="dispatched", tts=do_tts, chars=len(spoken.strip()),
             full_chars=len(full.strip()), attempts=attempts)
    except Exception:
        jlog("hook", status="error", stage="dispatch", tb=traceback.format_exc())


# ---------- manual catch-up ("batspeaker last") ----------

def find_active_transcript():
    """Most-recently-modified transcript across all Claude projects = the live
    session. Heuristic, but right in the common single-session case."""
    cands = glob.glob(os.path.expanduser("~/.claude/projects/*/*.jsonl"))
    return max(cands, key=os.path.getmtime) if cands else None


def last_n_turns_text(tpath, n, keep_narration=False):
    """Prose of each of the last n assistant turns, joined. With keep_narration
    the full turn (incl. pre-tool narration) is kept; otherwise just the final
    post-tool conclusion run."""
    turns, run = [], []

    def push():
        joined = "\n\n".join(c for c in run if c.strip())
        if joined.strip():
            turns.append(joined)

    with open(tpath) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
            except Exception:
                continue
            if is_real_user(e):
                push()
                run = []
            elif e.get("type") == "assistant":
                content = e.get("message", {}).get("content")
                if isinstance(content, list):
                    for b in content:
                        if not isinstance(b, dict):
                            continue
                        if b.get("type") == "text":
                            run.append(b.get("text", ""))
                        elif b.get("type") == "tool_use" and not keep_narration:
                            run = []
    push()
    return "\n\n".join(turns[-n:])


def cmd_last(n):
    """Manually TTS the last n turns on demand (toggle-independent)."""
    tpath = find_active_transcript()
    if not tpath:
        print("No transcript found.")
        return
    spoken = sanitize(last_n_turns_text(tpath, n))
    full = sanitize(last_n_turns_text(tpath, n, keep_narration=True))
    if len(spoken.strip()) < 1 and len(full.strip()) < 1:
        print("Last turn has no readable text yet (still generating?).")
        return
    if not spoken.strip():
        spoken = full
    pid = os.getpid()
    spoken_tmp = os.path.join("/tmp", f"batspeaker-last-{pid}.spoken.txt")
    full_tmp = os.path.join("/tmp", f"batspeaker-last-{pid}.full.txt")
    with open(spoken_tmp, "w") as f:
        f.write(spoken)
    with open(full_tmp, "w") as f:
        f.write(full)
    jlog("manual_last", turns=n, chars=len(spoken), full_chars=len(full),
         transcript=os.path.basename(tpath))
    worker(spoken_tmp, full_tmp)  # synchronous so the user gets immediate feedback
    print(f"Done — TTS'd the last {n} turn(s) into Bat-Speaker Live.")


# ---------- observability ("batspeaker stats") ----------

def cmd_stats():
    """Summarize the JSONL log: counts, cost estimate, race frequency, errors."""
    if not os.path.exists(LOG):
        print("No log yet.")
        return
    succ = skips = errors = dispatched = races = chars = dur = 0
    skip_reasons, err_stages, recent_errors = {}, {}, []
    with open(LOG) as f:
        for line in f:
            try:
                r = json.loads(line)
            except Exception:
                continue
            ev, st = r.get("event"), r.get("status")
            if ev == "hook" and st == "dispatched":
                dispatched += 1
                if (r.get("attempts") or 0) > 1:
                    races += 1
            elif ev == "hook" and st == "skip":
                skips += 1
                skip_reasons[r.get("reason")] = skip_reasons.get(r.get("reason"), 0) + 1
            elif ev == "worker" and st == "success":
                succ += 1
                chars += r.get("chars") or 0
                dur += r.get("duration") or 0
            elif st == "error":
                errors += 1
                err_stages[r.get("stage")] = err_stages.get(r.get("stage"), 0) + 1
                recent_errors.append(f"  {r.get('ts')}  {ev}/{r.get('stage')}")
    model = load_config().get("model", "tts-1-hd")
    rate = 30 if "hd" in model else 15
    cost = chars / 1_000_000 * rate
    print("Bat-Speaker stats")
    print(f"  clips produced : {succ}")
    print(f"  dispatched     : {dispatched}  (race-retries: {races})")
    print(f"  skips          : {skips}  {skip_reasons or ''}")
    print(f"  errors         : {errors}  {err_stages or ''}")
    print(f"  audio total    : {dur}s across {chars} chars")
    print(f"  est. spend     : ${cost:.3f}  (OpenAI {model} @ ${rate}/1M)")
    if recent_errors:
        print("  recent errors:")
        for line in recent_errors[-5:]:
            print(line)


def cmd_clear():
    """Wipe the Live note back to its header and delete every clip MP3.
    Only touches MP3_DIR (batspeaker/), so standalone test/comparison clips
    in the parent Attachments folder are left alone."""
    removed = 0
    for path in glob.glob(os.path.join(MP3_DIR, "*.mp3")):
        try:
            os.remove(path)
            removed += 1
        except Exception:
            pass
    write_note([], load_config()["keep"])
    jlog("clear", removed=removed)
    print(f"Cleared Bat-Speaker Live and deleted {removed} clip(s). Clean slate.")


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "--worker":
        spoken_f = sys.argv[2]
        full_f = sys.argv[3] if len(sys.argv) >= 4 else None
        tts_flag = (sys.argv[4] != "0") if len(sys.argv) >= 5 else True
        worker(spoken_f, full_f, tts=tts_flag)
    elif len(sys.argv) >= 2 and sys.argv[1] == "--clear":
        cmd_clear()
    elif len(sys.argv) >= 2 and sys.argv[1] == "--last":
        cmd_last(int(sys.argv[2]) if len(sys.argv) >= 3 else 1)
    elif len(sys.argv) >= 2 and sys.argv[1] == "--stats":
        cmd_stats()
    else:
        hook_entry()
