#!/usr/bin/env python3
"""
make_bucket.py — generate cleanup bucket files from a Reader tag.

Pulls every Reader document carrying a given tag (authoritative, live) and writes
bucket file(s) of document IDs for readwise_reader_cleanup.py to consume. Optionally
splits into one file per calendar month (by created_at) so big tags can be deleted
in reviewable chunks.

Usage:
  source ~/.env.sh && python3 make_bucket.py morning-brief --split-month
  source ~/.env.sh && python3 make_bucket.py prep
  source ~/.env.sh && python3 make_bucket.py weekly-review --exclude-tag bruce-panel prep
"""
import os
import sys
import json
import time
import argparse
import urllib.request
import urllib.error

API = "https://readwise.io/api/v3"
TOKEN = os.environ.get("READWISE_TOKEN")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "cleanup_buckets")


def die(m):
    print(f"ERROR: {m}", file=sys.stderr)
    sys.exit(1)


def req(url, max_retries=5):
    if not TOKEN:
        die("READWISE_TOKEN not set. Run: source ~/.env.sh")
    headers = {"Authorization": f"Token {TOKEN}"}
    for _ in range(max_retries):
        r = urllib.request.Request(url, headers=headers, method="GET")
        try:
            with urllib.request.urlopen(r) as resp:
                return json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            if e.code == 429:
                wait = int(e.headers.get("Retry-After", "5"))
                print(f"  rate-limited; waiting {wait}s...", file=sys.stderr)
                time.sleep(wait + 1)
                continue
            die(f"HTTP {e.code}: {e.read().decode(errors='replace')}")
        except urllib.error.URLError as e:
            print(f"  net error {e}; retrying", file=sys.stderr)
            time.sleep(3)
    die("request failed")


def normalize_tags(tags):
    if not tags:
        return set()
    if isinstance(tags, dict):
        return set(tags.keys())
    out = set()
    for t in tags:
        out.add(t if isinstance(t, str) else t.get("name"))
    return out


def fetch_tag(tag):
    docs, cursor = [], None
    while True:
        url = f"{API}/list/?tag={tag}"
        if cursor:
            url += f"&pageCursor={cursor}"
        payload = req(url)
        docs.extend(payload.get("results", []))
        cursor = payload.get("nextPageCursor")
        if not cursor:
            break
        time.sleep(0.4)
    return docs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tag")
    ap.add_argument("--split-month", action="store_true")
    ap.add_argument("--exclude-tag", nargs="*", default=[], help="skip docs carrying any of these tags")
    ap.add_argument("--require-tag", nargs="*", default=[], help="keep only docs carrying ALL of these tags")
    args = ap.parse_args()

    docs = fetch_tag(args.tag)
    excl = set(args.exclude_tag)
    reqd = set(args.require_tag)
    kept = []
    for d in docs:
        tags = normalize_tags(d.get("tags"))
        if excl and (tags & excl):
            continue
        if reqd and not (reqd <= tags):
            continue
        kept.append(d)

    print(f"tag '{args.tag}': {len(docs)} docs, {len(kept)} kept "
          f"(excludes {sorted(excl) or '(none)'}, requires {sorted(reqd) or '(none)'})")

    groups = {}
    for d in kept:
        key = (d.get("created_at") or "0000-00")[:7] if args.split_month else "all"
        groups.setdefault(key, []).append(d)

    os.makedirs(OUT_DIR, exist_ok=True)
    for key in sorted(groups):
        ds = sorted(groups[key], key=lambda x: x.get("created_at") or "")
        safe = args.tag.replace("/", "-")
        fname = f"{safe}_{key}.txt" if args.split_month else f"{safe}.txt"
        path = os.path.join(OUT_DIR, fname)
        with open(path, "w") as f:
            f.write(f"# Bucket — tag:{args.tag}  group:{key}  ({len(ds)} docs)  generated by make_bucket.py\n")
            for d in ds:
                cat = d.get("category")
                f.write(f"{d['id']}  # [{cat}] {d.get('title')}\n")
        # safety surface: report any non-article so the operator sees it before deleting
        nonart = [d for d in ds if d.get("category") != "article"]
        flag = f"  ⚠ {len(nonart)} NON-ARTICLE" if nonart else ""
        print(f"  wrote {fname}: {len(ds)} docs{flag}")
        for d in nonart:
            print(f"      NON-ARTICLE: {d['id']} [{d.get('category')}] {d.get('title')}")


if __name__ == "__main__":
    main()
